services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/var/www/html/index.html
    networks:
      lab-webproxy:
        ipv4_address: 172.31.0.6  # <-- Changed to new subnet

networks:
  lab-webproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16   # <-- Changed to new subnet
          gateway: 172.31.0.1
